using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;
using System.Drawing;
using System.Windows.Forms;
using SharpTools;

namespace SoundManager
{
    /// <summary>
    /// Export routine for Theme Pack file format for Windows 7 and greater
    /// </summary>
    static class SoundArchiveThemepack
    {
        public const string FileExtension = "themepack";
        private const string SpecificationsUrl = "https://learn.microsoft.com/en-us/windows/win32/controls/themesfileformat-overview";

        private const string FileNameTheme = "Scheme.theme";
        private const string FileNameDdf = "Scheme.ddf";
        private const string FileNameCab = "Scheme." + FileExtension;
        private static string FileNameLogo = RuntimeConfig.AppInternalName + ".png";

        /// <summary>
        /// Export the SoundManager sound scheme to the specified Themepack file
        /// </summary>
        /// <param name="themepackfile">Output Themepack file</param>
        public static void Export(string themepackfile)
        {
            string tempFolder = MakeTempFolder();
            try
            {
                foreach (SoundEvent soundEvent in SoundEvent.GetAll())
                {
                    if (File.Exists(soundEvent.FilePath))
                    {
                        File.Copy(soundEvent.FilePath, Path.Combine(tempFolder, soundEvent.FileName));
                    }
                }

                // Extract application icon for use as brand image
                IconExtractor.ExtractAssociatedIcon(Application.ExecutablePath)
                        .ToBitmap()
                            .Save(Path.Combine(tempFolder, FileNameLogo), System.Drawing.Imaging.ImageFormat.Png);

                // We need a valid wallpaper image file for making a valid Themepack file. Use sound scheme image, or program icon as fallback.
                if (File.Exists(SchemeMeta.SchemeImageFilePath))
                {
                    File.Copy(SchemeMeta.SchemeImageFilePath, Path.Combine(tempFolder, SchemeMeta.SchemeImageFileName));
                }
                else
                {
                    File.Copy(Path.Combine(tempFolder, FileNameLogo), Path.Combine(tempFolder, SchemeMeta.SchemeImageFileName));
                }

                GenerateThemeFile(tempFolder);
                GenerateCabDefinitionFile(tempFolder);
                RunMakeCab(tempFolder);

                if (File.Exists(Path.Combine(tempFolder, FileNameCab)))
                    File.Copy(Path.Combine(tempFolder, FileNameCab), themepackfile, true);
            }
            finally
            {
                Directory.Delete(tempFolder, true);
            }
        }

        /// <summary>
        /// Make a new temporary folder in %temp%
        /// </summary>
        /// <returns>Full path to newly created temporary folder</returns>
        private static string MakeTempFolder()
        {
            string tempPath = Path.GetTempPath();
            string tempSubfolder;
            do {
                tempSubfolder = Path.Combine(tempPath, Path.GetRandomFileName());
            } while (Directory.Exists(tempSubfolder));
            Directory.CreateDirectory(tempSubfolder);
            return tempSubfolder;
        }

        /// <summary>
        /// Generate .theme file at the desired location
        /// </summary>
        /// <param name="folderPath">Temporary Working directory</param>
        private static void GenerateThemeFile(string folderPath)
        {
            List<string> themeFile = new List<string>();
            themeFile.AddRange(new string[] {
                "; Generated by " + RuntimeConfig.AppInternalName,
                "; " + RuntimeConfig.ProjectRepositoryUrl,
                "",
                "[Theme]",
                "DisplayName=" + SchemeMeta.Name,
                "BrandImage=" + FileNameLogo,
                "",
                "; Below sections are mandatory for the theme to load properly",
                "; Users will need to set back their wallpaper after importing",
                "; " + SpecificationsUrl,
                "",
                "[MasterThemeSelector]",
                "MTSM=DABJDKT",
                "",
                @"[Control Panel\Desktop]",
                "Wallpaper=" + SchemeMeta.SchemeImageFileName,
                "TileWallpaper=0",
                "WallpaperStyle=0",
                "",
                "[VisualStyles]",
                @"Path=%SystemRoot%\resources\Themes\Aero\Aero.msstyles",
                "ColorStyle=NormalColor",
                "Size=NormalSize",
                "",
                "; Sound Scheme definition",
                "",
                "[Sounds]",
                "; IDS_SCHEME_DEFAULT",
                "SchemeName=" + SchemeMeta.Name,
                ""
            });
            foreach (SoundEvent soundEvent in SoundEvent.GetAll())
            {
                string fileName = null;

                if (File.Exists(soundEvent.FilePath))
                {
                    fileName = soundEvent.FileName;
                }
                else if (soundEvent.Type == SoundEvent.EventType.LoadScheme)
                {
                    SoundEvent eventToPlayOnLoad = SchemeMeta.EventToPlayOnLoad;
                    if (File.Exists(eventToPlayOnLoad.FilePath))
                        fileName = eventToPlayOnLoad.FileName;
                }

                if (fileName != null)
                {
                    foreach (string registryKey in soundEvent.RegistryKeys)
                    {
                        themeFile.AddRange(new string[] {
                            "[" + SoundScheme.RegApps + registryKey + "]",
                            "DefaultValue=" + fileName,
                            ""
                        });
                    }
                }
            }
            File.WriteAllLines(Path.Combine(folderPath, FileNameTheme), themeFile, Encoding.Default);
        }

        /// <summary>
        /// Generate DDF Cabinet file definition for Makecab
        /// </summary>
        /// <param name="folderPath">Temporary Working directory</param>
        private static void GenerateCabDefinitionFile(string folderPath)
        {
            List<string> cabFileDefinition = new List<string>();
            cabFileDefinition.AddRange(new string[] {
                ".OPTION EXPLICIT",
                ".Set CabinetNameTemplate=" + FileNameCab,
                ".Set Cabinet=on",
                ".Set Compress=on",
                ".Set CabinetFileCountThreshold=0",
                ".Set FolderFileCountThreshold=0",
                ".Set FolderSizeThreshold=0",
                ".Set MaxCabinetSize=0",
                ".Set MaxDiskFileCount=0",
                ".Set MaxDiskSize=0",
                ".Set DiskDirectory1=."
            });
            foreach (SoundEvent soundEvent in SoundEvent.GetAll())
            {
                if (File.Exists(soundEvent.FilePath))
                {
                    cabFileDefinition.Add("\"" + soundEvent.FileName + "\"");
                }
            }
            cabFileDefinition.Add("\"" + FileNameLogo + "\"");
            cabFileDefinition.Add("\"" + SchemeMeta.SchemeImageFileName + "\"");
            cabFileDefinition.Add("\"" + FileNameTheme + "\"");
            File.WriteAllLines(Path.Combine(folderPath, FileNameDdf), cabFileDefinition);
        }

        /// <summary>
        /// Generate CAB file using the DDF Cafinet file definition
        /// </summary>
        /// <param name="folderPath">Temporary Working directory</param>
        /// <param name="cabDefinitionFile"></param>
        private static void RunMakeCab(string folderPath)
        {
            ProcessStartInfo makecab = new ProcessStartInfo();
            makecab.FileName = "makecab";
            makecab.Arguments = "/F " + FileNameDdf;
            makecab.WorkingDirectory = folderPath;
            makecab.WindowStyle = ProcessWindowStyle.Hidden;
            makecab.CreateNoWindow = true;
            Process.Start(makecab).WaitForExit();
        }
    }
}
